language: julia
os:
    - osx
julia:
    - 1.3
    - 1.4
    - nightly
env:
  - JULIA_PROJECT="@."
notifications:
    email: false
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
